language: cpp

python:
- "2.7"

sudo: required

script:
- mbed new .
- sudo pip install -r mbed-os/requirements.txt
- mbed compile --clean -m NUCLEO_L432KC -t GCC_ARM

before_install:
- sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
- sudo apt-get update -qq
- sudo apt-get install -qq --allow-unauthenticated gcc-arm-none-eabi

install:
- sudo pip install mbed-cli
